export const adminResourceConfigs = [
  {
    slug: "brands",
    title: "Brands",
    endpoint: "/api/brands",
    idKey: "brandId",
    columns: [
      { key: "brandId", label: "ID" },
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "isActive", label: "Active", render: (row) => String(row.isActive ?? row.active) },
    ],
    formFields: [
      { name: "name", label: "Brand Name", type: "text" },
      { name: "slug", label: "Slug", type: "text" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    initialValues: { name: "", slug: "", isActive: true },
  },
  {
    slug: "categories",
    title: "Categories",
    endpoint: "/api/categories",
    idKey: "categoryId",
    columns: [
      { key: "categoryId", label: "ID" },
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "parentCategoryName", label: "Parent" },
      { key: "isActive", label: "Active", render: (row) => String(row.isActive ?? row.active) },
    ],
    formFields: [
      { name: "name", label: "Category Name", type: "text" },
      { name: "slug", label: "Slug", type: "text" },
      { name: "parentCategoryId", label: "Parent Category ID", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    initialValues: { name: "", slug: "", parentCategoryId: "", isActive: true },
  },
  {
    slug: "products",
    title: "Products",
    endpoint: "/api/products",
    idKey: "productId",
    columns: [
      { key: "productId", label: "ID" },
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "categoryName", label: "Category" },
      { key: "brandName", label: "Brand" },
      { key: "status", label: "Status" },
    ],
    formFields: [
      { name: "categoryId", label: "Category ID", type: "number" },
      { name: "brandId", label: "Brand ID", type: "number" },
      { name: "name", label: "Product Name", type: "text" },
      { name: "slug", label: "Slug", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "ACTIVE", "ARCHIVED"] },
    ],
    initialValues: { categoryId: "", brandId: "", name: "", slug: "", description: "", status: "ACTIVE" },
  },
  {
    slug: "product-variants",
    title: "Product Variants",
    endpoint: "/api/product-variants",
    idKey: "productVariantId",
    columns: [
      { key: "productVariantId", label: "ID" },
      { key: "productName", label: "Product" },
      { key: "variantName", label: "Variant" },
      { key: "sku", label: "SKU" },
      { key: "price", label: "Price", type: "currency" },
      { key: "discountPrice", label: "Discount", type: "currency" },
      { key: "status", label: "Status" },
    ],
    formFields: [
      { name: "productId", label: "Product ID", type: "number" },
      { name: "sku", label: "SKU", type: "text" },
      { name: "variantName", label: "Variant Name", type: "text" },
      { name: "price", label: "Price", type: "number" },
      { name: "discountPrice", label: "Discount Price", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "ARCHIVED"] },
    ],
    initialValues: { productId: "", sku: "", variantName: "", price: "", discountPrice: "", status: "ACTIVE" },
  },
  {
    slug: "variant-inventories",
    title: "Variant Inventories",
    endpoint: "/api/variant-inventories",
    idKey: "productVariantId",
    columns: [
      { key: "productVariantId", label: "Variant ID" },
      { key: "productVariantName", label: "Variant Name" },
      { key: "stockQty", label: "Stock" },
      { key: "reservedQty", label: "Reserved" },
    ],
    formFields: [
      { name: "productVariantId", label: "Product Variant ID", type: "number" },
      { name: "stockQty", label: "Stock Quantity", type: "number" },
      { name: "reservedQty", label: "Reserved Quantity", type: "number" },
    ],
    initialValues: { productVariantId: "", stockQty: 0, reservedQty: 0 },
    idReadOnlyOnEdit: true,
  },
  {
    slug: "stock-movements",
    title: "Stock Movements",
    endpoint: "/api/stock-movements",
    idKey: "stockMovementId",
    columns: [
      { key: "stockMovementId", label: "ID" },
      { key: "productVariantName", label: "Variant" },
      { key: "movementType", label: "Movement Type" },
      { key: "quantity", label: "Qty" },
      { key: "reason", label: "Reason" },
      { key: "createdByUserName", label: "Created By" },
    ],
    formFields: [
      { name: "productVariantId", label: "Product Variant ID", type: "number" },
      { name: "movementType", label: "Movement Type", type: "select", options: ["IN", "OUT", "RESERVE", "RELEASE", "ADJUST"] },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "reason", label: "Reason", type: "text" },
      { name: "referenceType", label: "Reference Type", type: "text" },
      { name: "referenceId", label: "Reference ID", type: "number" },
    ],
    initialValues: { productVariantId: "", movementType: "IN", quantity: 1, reason: "", referenceType: "ADMIN", referenceId: "" },
    disableDelete: true,
    disableEdit: true,
  },
  {
    slug: "coupons",
    title: "Coupons",
    endpoint: "/api/coupons",
    idKey: "couponId",
    columns: [
      { key: "couponId", label: "ID" },
      { key: "code", label: "Code" },
      { key: "discountType", label: "Type" },
      { key: "discountValue", label: "Value", type: "currency" },
      { key: "minOrderValue", label: "Min Order", type: "currency" },
      { key: "isActive", label: "Active", render: (row) => String(row.isActive ?? row.active) },
    ],
    formFields: [
      { name: "code", label: "Code", type: "text" },
      { name: "discountType", label: "Discount Type", type: "select", options: ["PERCENT", "FIXED"] },
      { name: "discountValue", label: "Discount Value", type: "number" },
      { name: "minOrderValue", label: "Minimum Order Value", type: "number" },
      { name: "startsAt", label: "Starts At", type: "datetime-local" },
      { name: "endsAt", label: "Ends At", type: "datetime-local" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    initialValues: { code: "", discountType: "PERCENT", discountValue: "", minOrderValue: 0, startsAt: "", endsAt: "", isActive: true },
  },
  {
    slug: "product-images",
    title: "Product Images",
    endpoint: "/api/product-images",
    idKey: "productImageId",
    columns: [
      { key: "productImageId", label: "ID" },
      { key: "productName", label: "Product" },
      { key: "url", label: "Image URL" },
      { key: "isPrimary", label: "Primary", render: (row) => String(row.isPrimary ?? row.primary) },
    ],
    formFields: [
      { name: "productId", label: "Product ID", type: "number" },
      { name: "url", label: "Image URL", type: "text" },
      { name: "isPrimary", label: "Primary", type: "checkbox" },
    ],
    initialValues: { productId: "", url: "", isPrimary: false },
  },
  {
    slug: "product-spec-attributes",
    title: "Product Spec Attributes",
    endpoint: "/api/product-spec-attributes",
    idKey: "productSpecAttributeId",
    columns: [
      { key: "productSpecAttributeId", label: "ID" },
      { key: "categoryName", label: "Category" },
      { key: "name", label: "Name" },
      { key: "dataType", label: "Data Type" },
      { key: "isRequired", label: "Required", render: (row) => String(row.isRequired ?? row.required) },
      { key: "isFilterable", label: "Filterable", render: (row) => String(row.isFilterable ?? row.filterable) },
      { key: "isActive", label: "Active", render: (row) => String(row.isActive ?? row.active) },
    ],
    formFields: [
      { name: "categoryId", label: "Category ID", type: "number" },
      { name: "name", label: "Name", type: "text" },
      { name: "dataType", label: "Data Type", type: "select", options: ["TEXT", "NUMBER", "BOOLEAN"] },
      { name: "isRequired", label: "Required", type: "checkbox" },
      { name: "isFilterable", label: "Filterable", type: "checkbox" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    initialValues: { categoryId: "", name: "", dataType: "TEXT", isRequired: false, isFilterable: false, isActive: true },
  },
  {
    slug: "variant-attributes",
    title: "Variant Attributes",
    endpoint: "/api/variant-attributes",
    idKey: "variantAttributeId",
    columns: [
      { key: "variantAttributeId", label: "ID" },
      { key: "name", label: "Name" },
    ],
    formFields: [
      { name: "name", label: "Name", type: "text" },
    ],
    initialValues: { name: "" },
  },
  {
    slug: "variant-attribute-values",
    title: "Variant Attribute Values",
    endpoint: "/api/variant-attribute-values",
    idKey: "variantAttributeValueId",
    columns: [
      { key: "variantAttributeValueId", label: "ID" },
      { key: "productVariantName", label: "Variant" },
      { key: "variantAttributeName", label: "Attribute" },
      { key: "value", label: "Value" },
    ],
    formFields: [
      { name: "productVariantId", label: "Product Variant ID", type: "number" },
      { name: "variantAttributeId", label: "Variant Attribute ID", type: "number" },
      { name: "value", label: "Value", type: "text" },
    ],
    initialValues: { productVariantId: "", variantAttributeId: "", value: "" },
  }

];
